version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  publish:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: pip install twine && twine upload

workflows:
  main:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest
      - publish
